### ISSUE TITLE
(feature) Add ability to disable content-length header

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/shelf_static#16]
Since `shelf.addChunkedEncoding` requires that the response contentLength be null, it would be nice to be able to prevent the static handler from adding the content length so that files can be gzipped.

**Comment by nex3** [comment]
I'm not sure what `shelf.addChunkedEncoding` has to do with gzip...

**Comment by johnpryan** [comment]
As far as I can tell, the `transfer-encoding` header needs to be set to 'chunked' along with `Content-encoding` set to `gzip` in order for responses to be compressed: https://en.wikipedia.org/wiki/Chunked_transfer_encoding#Use_with_compression

**Comment by johnpryan** [comment]
This is also problematic because once the `content-length` header is added it cannot be removed by other middleware (`Response.change()` disallows removing headers

**Comment by nex3** [comment]
> As far as I can tell, the `transfer-encoding` header needs to be set to 'chunked' along with `Content-encoding` set to `gzip` in order for responses to be compressed: https://en.wikipedia.org/wiki/Chunked_transfer_encoding#Use_with_compression

I don't think that's accurate. I believe all that article is saying is that, *if* you want to both gzip and chunk a request, the gzip happens before the chunking.

This is borne out by empirical testing. The following program (using shelf 0.6.7+2) works with `curl --compressed http://localhost:1234`:

```dart
import 'dart:io';

import "package:shelf/shelf.dart";
import "package:shelf/shelf_io.dart" as io;

main() {
  io.serve((request) {
    return new Response.ok(
        ZLIB.encode("hi!".codeUnits),
        headers: {'content-encoding': 'gzip'});
  }, 'localhost', 1234);
}
```

> This is also problematic because once the `content-length` header is added it cannot be removed by other middleware (`Response.change()` disallows removing headers

You can pass `null` as a header value to (effectively) remove that header.

**Comment by johnpryan** [comment]
After looking into this some more, I think the problem I am having is related to setting `HttpServer.autoCompress` to true.  From the `autoCompress` documentation:

 >  The content can only be compressed when the response is using chunked Transfer-Encoding and the incoming request has gzip as an accepted encoding in the Accept-Encoding header.

**Comment by johnpryan** [comment]
> You can pass null as a header value to (effectively) remove that header.

That didn't work for me, becase shelf assumes that there is an integer value in that header:

```
  /// The contents of the content-length field in [headers].
  ///
  /// If not set, `null`.
  int get contentLength {
    if (_contentLengthCache != null) return _contentLengthCache;
    if (!headers.containsKey('content-length')) return null;
    _contentLengthCache = int.parse(headers['content-length']);
    return _contentLengthCache;
  }
```

**Comment by nex3** [comment]
> After looking into this some more, I think the problem I am having is related to setting `HttpServer.autoCompress` to true.  From the `autoCompress` documentation:
>
>  >  The content can only be compressed when the response is using chunked Transfer-Encoding and the incoming request has gzip as an accepted encoding in the Accept-Encoding header.

This is bizarre behavior on `dart:io`'s part. As far as I can tell from the spec and actual client behavior this is a totally unnecessary restriction. I'd suggest filing a bug against the SDK to change the behavior, and for now avoiding that flag and implementing your own GZIP middleware using the zlib codec. Bonus: it'll work the same if you ever change your server implementation!

> That didn't work for me, because shelf assumes that there is an integer value in that header:
> 
> ```
>   /// The contents of the content-length field in [headers].
>   ///
>   /// If not set, `null`.
>   int get contentLength {
>     if (_contentLengthCache != null) return _contentLengthCache;
>     if (!headers.containsKey('content-length')) return null;
>     _contentLengthCache = int.parse(headers['content-length']);
>     return _contentLengthCache;
>   }
> ```

Ah, good point. We should probably explicitly delete any headers with `null` values to avoid issues like this. I've filed dart-lang/shelf#68 to track this.

If you really want to force a chunked transfer-encoding, you can modify your request so that the body is a Stream and shelf can't efficiently determine its length.

**Comment by johnpryan** [comment]
Thanks for looking into this.  I'm not sure gzip middleware is necessary after all.  The following script works just fine:

```
import 'dart:async';

import 'dart:io';
import 'package:path/path.dart';
import "package:shelf/shelf.dart";
import "package:shelf_static/shelf_static.dart";
import "package:shelf/shelf_io.dart" as io;

main() async {
  var directory = dirname(Platform.script.toFilePath());
  var server = await io.serve(
      createStaticHandler(directory, defaultDocument: 'server.dart'),
      '0.0.0.0',
      1234);
  server.autoCompress = true;
}
```

running `dart server.dart` and `curl --compressed http://localhost:1234` prints the contents of the script as expected

**Comment by johnpryan** [comment]
however using `curl http://localhost:1234` also returns the script source, so the file is not being compressed after all.

**Comment by johnpryan** [comment]
> As far as I can tell from the spec and actual client behavior this is a totally unnecessary restriction

Here's some GZIP middleware:

```
final gzipMiddleware =
    shelf.createMiddleware(responseHandler: (response) async {
  var newHeaders = new Map<String, String>.from(response.headers);
  var newBody = ZLIB.encode((await response.readAsString()).codeUnits);
  newHeaders[HttpHeaders.CONTENT_ENCODING] = 'gzip';
  newHeaders[HttpHeaders.CONTENT_LENGTH] = newBody.length.toString();
  var newResponse =
      response.change(headers: newHeaders, body: newBody);
  return newResponse;
});
```

This successfully encodes the body such that `curl --compress` can decode it.  However, Chrome does not honor the request and returns a `temporarily down` message.

**Comment by nex3** [comment]
It looks like the `ZLIB` constant doesn't actually have gzip enabled for some reason, and curl is more forgiving than Chrome. You'll need to construct your own `ZLibEncoder`. Here's a server that works for Chrome:

```dart
import 'dart:io';

import "package:shelf/shelf.dart";
import "package:shelf/shelf_io.dart" as io;

final gzip = new ZLibEncoder(gzip: true);

main() {
  io.serve((request) {
    return new Response.ok(
        gzip.convert("hi!".codeUnits),
        headers: {'content-encoding': 'gzip'});
  }, 'localhost', 1234);
}
```

Also, make sure to check that the Accept-Encoding header includes gzip before you serve a gzipped response.
