### ISSUE TITLE
Don't use *Sync methods in filesystem access.

### ISSUE THREAD

**Issue by isoos** [dart-lang/shelf_static#25]
They are blocking other processing that could go on while the file or directory is being read.

**Comment by kevmoo** [comment]
Thoughts, @nex3 ?

I'm happy to go all async here – but that also has runtime costs and makes debugging harder.

Maybe just use async when the operation could be long?

**Comment by nex3** [comment]
My experience has generally been that the overhead of async IO is high enough that it doesn't provide a meaningful performance benefit, even in the presence of some amount of parallelism. I wouldn't advise doing this without benchmarks that show a concrete benefit.

**Comment by isoos** [comment]
I stand corrected. The change was easy (I can send PR if interested), but the performance benefits were not measurable on my Linux server with a fast SSD, and were under 1-5% difference between the two. Not sure if a slower HDD would show a difference. On a Mac notebook the benchmark's result varied more than 30% between consecutive measurements, so I've discarded that.

**Comment by srawlins** [comment]
All use of `sync*` has been removed from this repo.
