### ISSUE TITLE
Stop using scheduled_test

### ISSUE THREAD

**Issue by srawlins** [dart-lang/shelf_static#26]
The `scheduled_test` package is no longer being maintained. shelf_static should switch to using `test` directly, probably along with the `test_descriptor` package.

**Comment by kevmoo** [comment]
Kevin from October agrees w/ you 😜 

https://github.com/dart-lang/shelf_static/commit/3558aa35a0d2f0f35868c3fd64b258e140db0122

**Comment by srawlins** [comment]
Brain fart. Dunno how I missed that. It's still used by SDK maybe...
