### ISSUE TITLE
How to close the server?

### ISSUE THREAD

**Issue by Nightmare-MY** [dart-lang/shelf_static#65]
i use it for my flutter app,i want close the server and not close my app,any help thanks~

**Comment by kevmoo** [comment]
Are you running the server with your app? `ctrl-c` from the command line should work.

Are you running it with your IDE?

**Comment by Nightmare-MY** [comment]
In fact,I don't use it on the command line,i use it on flutter app,like [speedshare](https://github.com/nightmare-space/speed_share),i think shelf can also support client,and it worked nice,but i can't close it by dart.

**Comment by Nightmare-MY** [comment]
i think shelf should support close invoked like HttpServer or the other server framework.

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/samples/blob/master/server/simple/bin/server.dart#L26

You get a server instance. You can call `close` on it.
