### ISSUE TITLE
createStaticHandler not working on macOS (desktop) target

### ISSUE THREAD

**Issue by sinapsi** [dart-lang/shelf_static#69]
var staticHandler = createStaticHandler('path/path', defaultDocument: 'index.html');

does not work for macOS.

The error is:
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): A directory corresponding to fileSystemPath "path/path" could not be found

**Comment by kevmoo** [comment]
Does that directory exist? Relative to the package you're running?

**Comment by sinapsi** [comment]
The directory exists, it is in the root of the project. I don’t have the
same issue on windows target--
Michele Rappazzo

**Comment by kevmoo** [comment]
Weird! Does it work with an absolute path?

**Comment by sinapsi** [comment]
with absolute path i don't have that error, but when i try to reach the content with a browser:
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot open file, path = '[full path]' (OS Error: Operation not permitted, errno = 1)

**Comment by kevmoo** [comment]
I've done a LOT of development with this package on my mac w/ no issue.

Are you on the latest Mac OS version? Are you trying to host content in a protected directory?

**Comment by sinapsi** [comment]
> Are you on the latest Mac OS version?
yes, Big Sur 11.6 (20G165)
> Are you trying to host content in a protected directory?
I have the project in a directory in my desktop 🤷‍♂️

**Comment by kevmoo** [comment]
Desktop! I bet this is a security thing!

**Comment by sinapsi** [comment]
i moved the project outside the desktop (in a subdirectory of my home) and now works.
I put it again in the desktop and it works as well 🤷‍♂️

**Comment by kevmoo** [comment]
Ha! this is absolutely not a `shelf_static` issue. Something between mac and the VM. Glad it works now!

**Comment by sinapsi** [comment]
i am sorry, i still have the same problem.
Yesterday it worked because (i think) i put manually the folder in /Users/michele/Library/Containers/[appname]/Data/
should i do this?
