### ISSUE TITLE
Add option to Override Headers 

### ISSUE THREAD

**Issue by filipenanclarez** [dart-lang/shelf_static#71]
I need to set ACCESS_CONTROL_ALLOW_ORIGIN: '*' because i got erros when try load .ttf fonts with static server.

I try to do with shelf_cors_headers but without success.

Can you add option to override Headers? Or can i do this with another way? If exist please let me know.

**Comment by kevmoo** [comment]
You just need to wrap the static handler with [middleware](https://pub.dev/documentation/shelf/latest/shelf/Middleware.html).

**Comment by filipenanclarez** [comment]
> You just need to wrap the static handler with [middleware](https://pub.dev/documentation/shelf/latest/shelf/Middleware.html).

Can show me a simple example? I try it, but not succes.
