### ISSUE TITLE
feat(shelf_static): Add a template engine to inject values on static files

### ISSUE THREAD

**Issue by albertodev01** [dart-lang/shelf_static#72]
I haven't been able to find this feature but I'm willing to help with a PR if needed! 

---

Imagine having this page in a file called `index.html`:

```html
<html>
<body>
<p>Hello, my name is {:name} and I am {:my_age} years old</p>
</body>
</html>
```

I would like to be able to replace `{:name}` and `{:my_age}` with some values coming from Dart, like this:

```dart
final indexPageValues = PageValues(
  file: 'index.html',
  values: {
    'name': 'Alberto',
    'my_age': 25,
  },
);

shelf_static.createStaticHandler(
  'public', 
  defaultDocument: 'index.html',
 
  // add this param
  pageValues: <PageValues>[
    indexPageValues,
  ],
);
```

In this way, the `{:some_name}` tags in the HTML code will be replaced by the values provided via Dart. The result would be

```html
<html>
<body>
<p>Hello, my name is Alberto and I am 25 years old</p>
</body>
</html>
```

This would also allow custom HTML processed from Dart.

---

Please take the the `{:some_name}` syntax as example, don't focus on it. Focus on the general idea instead: might this be good? 🙂  what could I improve to make this look better?

Thank you!

**Comment by kevmoo** [comment]
Building such a feature would be straight-forward, but that wouldn't fit into `shelf_static`. This package is explicitly (and narrowly) focused on being a solid static file handler.

**Comment by albertodev01** [comment]
Where could it be implemented then? Would it be in an existing package or in a brand new one?

**Comment by kevmoo** [comment]
I'd do it in a new package. Look at https://pub.dev/packages/shelf_mustache
